# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  #boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" "uas" "sd_mod" "ext4" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "console=tty1" "loglevel=7" "rd.systemd.log_level=debug" ];
  boot.initrd.systemd.enable = true;

  /*
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };
  */

  # ── Filesystem ─────────────────────────────────────────────────────────────
  # Struttura:
  # SD card (mmcblk0)
  # ├── p1  vfat   /boot/firmware   (boot, read-only nella pratica)
  # └── p2  ext4   /nix/store       (generazioni NixOS, read-only dopo il boot)

  # Chiavetta USB (sda)
  # └── p1  ext4   /persist         (tutto quello che sopravvive ai riavvii)

  # RAM
  # └── tmpfs      /                (root effimera, si azzera ad ogni riavvio)

  #   //nas/musica   →  /mnt/musica    (opzionale, nofail)
  # ───────────────────────────────────────────────────────────────────────────
  # ── Root su tmpfs — si azzera ad ogni riavvio ──────────────────────────
  fileSystems."/" = {
    device  = "none";
    fsType  = "tmpfs";
    options = [ "defaults" "size=1G" "mode=755" ];
  };

  # ── /nix sulla SD card — scritto solo da nixos-rebuild ────────────────
  fileSystems."/nix" = {
    device  = "/dev/disk/by-label/nixos-store";
    fsType  = "ext4";
    #options = [ "relatime" "commit=300" ];
    neededForBoot = true;
    options       = [ "x-systemd.makefs" "relatime" ];
  };

  # ── /persist sulla chiavetta USB — tutto ciò che sopravvive ──────────
  fileSystems."/persist" = {
    device        = "/dev/disk/by-uuid/6d26ad56-53c2-4051-9939-52f153d9d23c";
    fsType        = "ext4";
    #options       = [ "relatime" "commit=60" ];
    neededForBoot = true;
    options       = [ "x-systemd.makefs" "relatime" ];
  };

  # ── /boot/firmware sulla SD card ─────────────────────────────────────
  fileSystems."/boot/firmware" = {
    device  = "/dev/disk/by-label/FIRMWARE";
    fsType  = "vfat";
    options = [ "defaults" ];
  };

  /*
  # ── Mount NAS / USB esterno via SMB ───────────────────────────────────────
  # Il mount è opzionale: nofail + automount garantiscono che il sistema
  # si avvii normalmente anche se il NAS non è raggiungibile.
  #
  # Crea il file delle credenziali in /persist/smb-credentials con:
  #   username=tuoutente
  #   password=tuapassword
  # Poi: chmod 600 /persist/smb-credentials
  fileSystems."/mnt/musica" = {
      device  = "//192.168.1.X/musica";   # ← cambia con IP e share del tuo NAS
      fsType  = "cifs";
      options = [
        "credentials=/persist/smb-credentials"
        "uid=${toString config.users.users.mpd.uid}"  # MPD può leggere i file
        "gid=audio"
        "iocharset=utf8"
        "vers=3.0"
        "nofail"                          # non blocca il boot se assente
        "_netdev"                         # aspetta la rete prima di montare
        "x-systemd.automount"             # monta solo quando viene acceduto
        "x-systemd.idle-timeout=60"       # smonta dopo 60s di inattività
        "x-systemd.mount-timeout=10"      # timeout connessione NAS
        "x-systemd.requires=network-online.target"
      ];
    };

  # Assicura che systemd aspetti la rete prima del mount
  systemd.services."mnt-musica.mount" = {
      after   = [ "network-online.target" ];
      wants   = [ "network-online.target" ];
    };

  # Pacchetti necessari per CIFS
  environment.systemPackages = [ pkgs.cifs-utils ];
  */

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}

