# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d947dcf2-53cf-4c0e-ba1a-54dd4b47a57d";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d947dcf2-53cf-4c0e-ba1a-54dd4b47a57d";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d947dcf2-53cf-4c0e-ba1a-54dd4b47a57d";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DED7-56A7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  /*
  # ── Mount NAS / USB esterno via SMB ───────────────────────────────────────
  # Il mount è opzionale: nofail + automount garantiscono che il sistema
  # si avvii normalmente anche se il NAS non è raggiungibile.
  #
  # Crea il file delle credenziali in /persist/smb-credentials con:
  #   username=tuoutente
  #   password=tuapassword
  # Poi: chmod 600 /persist/smb-credentials
  fileSystems."/mnt/musica" = {
      device  = "//192.168.1.X/musica";   # ← cambia con IP e share del tuo NAS
      fsType  = "cifs";
      options = [
        "credentials=/persist/smb-credentials"
        "uid=${toString config.users.users.mpd.uid}"  # MPD può leggere i file
        "gid=audio"
        "iocharset=utf8"
        "vers=3.0"
        "nofail"                          # non blocca il boot se assente
        "_netdev"                         # aspetta la rete prima di montare
        "x-systemd.automount"             # monta solo quando viene acceduto
        "x-systemd.idle-timeout=60"       # smonta dopo 60s di inattività
        "x-systemd.mount-timeout=10"      # timeout connessione NAS
        "x-systemd.requires=network-online.target"
      ];
    };

  # Assicura che systemd aspetti la rete prima del mount
  systemd.services."mnt-musica.mount" = {
      after   = [ "network-online.target" ];
      wants   = [ "network-online.target" ];
    };

  # Pacchetti necessari per CIFS
  environment.systemPackages = [ pkgs.cifs-utils ];
  */

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}