# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  zramSwap = {
    enable        = true;
    algorithm     = "zstd";
    memoryPercent = 50;   # ~430MB su 1GB
  };

  swapDevices = [{
    device = "/var/lib/swapfile";
    size   = 1024;  # 1GB
  }];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
